// Generated by gencpp from file pose_estimator/PoseEstimationResponse.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATOR_MESSAGE_POSEESTIMATIONRESPONSE_H
#define POSE_ESTIMATOR_MESSAGE_POSEESTIMATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pose_estimator
{
template <class ContainerAllocator>
struct PoseEstimationResponse_
{
  typedef PoseEstimationResponse_<ContainerAllocator> Type;

  PoseEstimationResponse_()
    : detected_object_names()
    , detected_object_poses()  {
    }
  PoseEstimationResponse_(const ContainerAllocator& _alloc)
    : detected_object_names(_alloc)
    , detected_object_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _detected_object_names_type;
  _detected_object_names_type detected_object_names;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _detected_object_poses_type;
  _detected_object_poses_type detected_object_poses;





  typedef boost::shared_ptr< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseEstimationResponse_

typedef ::pose_estimator::PoseEstimationResponse_<std::allocator<void> > PoseEstimationResponse;

typedef boost::shared_ptr< ::pose_estimator::PoseEstimationResponse > PoseEstimationResponsePtr;
typedef boost::shared_ptr< ::pose_estimator::PoseEstimationResponse const> PoseEstimationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pose_estimator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pose_estimator': ['/home/agandhi2/mer_lab/ros_ws/src/projects/table_rearrange/pose_estimator/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa22b7ddcb05be0466df4bd0bd45e82";
  }

  static const char* value(const ::pose_estimator::PoseEstimationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa22b7ddcb05be0ULL;
  static const uint64_t static_value2 = 0x466df4bd0bd45e82ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_estimator/PoseEstimationResponse";
  }

  static const char* value(const ::pose_estimator::PoseEstimationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] detected_object_names\n\
geometry_msgs/Pose[] detected_object_poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::pose_estimator::PoseEstimationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detected_object_names);
      stream.next(m.detected_object_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseEstimationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_estimator::PoseEstimationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_estimator::PoseEstimationResponse_<ContainerAllocator>& v)
  {
    s << indent << "detected_object_names[]" << std::endl;
    for (size_t i = 0; i < v.detected_object_names.size(); ++i)
    {
      s << indent << "  detected_object_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detected_object_names[i]);
    }
    s << indent << "detected_object_poses[]" << std::endl;
    for (size_t i = 0; i < v.detected_object_poses.size(); ++i)
    {
      s << indent << "  detected_object_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.detected_object_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_ESTIMATOR_MESSAGE_POSEESTIMATIONRESPONSE_H
