// Generated by gencpp from file pose_estimator/PoseEstimation.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATOR_MESSAGE_POSEESTIMATION_H
#define POSE_ESTIMATOR_MESSAGE_POSEESTIMATION_H

#include <ros/service_traits.h>


#include <pose_estimator/PoseEstimationRequest.h>
#include <pose_estimator/PoseEstimationResponse.h>


namespace pose_estimator
{

struct PoseEstimation
{

typedef PoseEstimationRequest Request;
typedef PoseEstimationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseEstimation
} // namespace pose_estimator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_estimator::PoseEstimation > {
  static const char* value()
  {
    return "022a68c5fe014e6ff7c9f68c41199bb3";
  }

  static const char* value(const ::pose_estimator::PoseEstimation&) { return value(); }
};

template<>
struct DataType< ::pose_estimator::PoseEstimation > {
  static const char* value()
  {
    return "pose_estimator/PoseEstimation";
  }

  static const char* value(const ::pose_estimator::PoseEstimation&) { return value(); }
};


// service_traits::MD5Sum< ::pose_estimator::PoseEstimationRequest> should match 
// service_traits::MD5Sum< ::pose_estimator::PoseEstimation > 
template<>
struct MD5Sum< ::pose_estimator::PoseEstimationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_estimator::PoseEstimation >::value();
  }
  static const char* value(const ::pose_estimator::PoseEstimationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_estimator::PoseEstimationRequest> should match 
// service_traits::DataType< ::pose_estimator::PoseEstimation > 
template<>
struct DataType< ::pose_estimator::PoseEstimationRequest>
{
  static const char* value()
  {
    return DataType< ::pose_estimator::PoseEstimation >::value();
  }
  static const char* value(const ::pose_estimator::PoseEstimationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_estimator::PoseEstimationResponse> should match 
// service_traits::MD5Sum< ::pose_estimator::PoseEstimation > 
template<>
struct MD5Sum< ::pose_estimator::PoseEstimationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_estimator::PoseEstimation >::value();
  }
  static const char* value(const ::pose_estimator::PoseEstimationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_estimator::PoseEstimationResponse> should match 
// service_traits::DataType< ::pose_estimator::PoseEstimation > 
template<>
struct DataType< ::pose_estimator::PoseEstimationResponse>
{
  static const char* value()
  {
    return DataType< ::pose_estimator::PoseEstimation >::value();
  }
  static const char* value(const ::pose_estimator::PoseEstimationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_ESTIMATOR_MESSAGE_POSEESTIMATION_H
