urdf_file_name: "franka_camera_control.xacro"
fixed_frame: "panda_link0"
joint_names: [ [ "panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_hand_joint" ] ]
joint_ordering: [ "panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6" ]
ee_fixed_joints: [ "panda_hand_joint" ]
starting_config: [ -1.665586072885361e-05, 0.12182416845508737, 2.9801295087672486e-05, -0.3872721384553266, -8.403642048016025e-06, 0.09318564719063449 ]
collision_file_name: "collision_example_franka.yaml"
collision_nn_file: "franka_camera_control_nn"
path_to_src: "/home/ajay/kaam/DR/catkin_ws_dr/src/relaxed_ik/src"
axis_types: [ [ "z", "z", "z", "z", "z", "z" ] ]
velocity_limits: [ 2.175, 2.175, 2.175, 2.175, 2.61, 2.61 ]
joint_limits: [ [-2.8973,2.8973], [-1.7628,1.7628], [-2.8973,2.8973], [-3.0718,-0.0698], [-2.8973,2.8973], [-0.0175,3.7525] ]
displacements: [ [ [0.0,0.0,0.0], [0.0,-0.316,0.0], [0.0825,0.0,0.0], [-0.0825,0.384,0.0], [0.0,0.0,0.0], [0.1,-0.1,0.0], [0.1,-0.1,0.0] ] ]
disp_offsets: [ [0.0,0.0,0.333] ]
rot_offsets: [ [ [0.0,0.0,0.0], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [-1.57079632679,0.0,0.0], [1.57079632679,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0] ] ]
joint_types: [ [ "revolute", "revolute", "revolute", "revolute", "revolute", "revolute", "fixed" ] ]
joint_state_define_func_file: "franka_camera_control_joint_state_define"
