// Generated by gencpp from file franka_gripper_gazebo/GripMsgResponse.msg
// DO NOT EDIT!


#ifndef FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSGRESPONSE_H
#define FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_gripper_gazebo
{
template <class ContainerAllocator>
struct GripMsgResponse_
{
  typedef GripMsgResponse_<ContainerAllocator> Type;

  GripMsgResponse_()
    {
    }
  GripMsgResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripMsgResponse_

typedef ::franka_gripper_gazebo::GripMsgResponse_<std::allocator<void> > GripMsgResponse;

typedef boost::shared_ptr< ::franka_gripper_gazebo::GripMsgResponse > GripMsgResponsePtr;
typedef boost::shared_ptr< ::franka_gripper_gazebo::GripMsgResponse const> GripMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace franka_gripper_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_gripper_gazebo/GripMsgResponse";
  }

  static const char* value(const ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::franka_gripper_gazebo::GripMsgResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSGRESPONSE_H
