// Generated by gencpp from file franka_gripper_gazebo/GripMsg.msg
// DO NOT EDIT!


#ifndef FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSG_H
#define FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSG_H

#include <ros/service_traits.h>


#include <franka_gripper_gazebo/GripMsgRequest.h>
#include <franka_gripper_gazebo/GripMsgResponse.h>


namespace franka_gripper_gazebo
{

struct GripMsg
{

typedef GripMsgRequest Request;
typedef GripMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripMsg
} // namespace franka_gripper_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_gripper_gazebo::GripMsg > {
  static const char* value()
  {
    return "e18a51329659ac6263f87aaf9a01fe62";
  }

  static const char* value(const ::franka_gripper_gazebo::GripMsg&) { return value(); }
};

template<>
struct DataType< ::franka_gripper_gazebo::GripMsg > {
  static const char* value()
  {
    return "franka_gripper_gazebo/GripMsg";
  }

  static const char* value(const ::franka_gripper_gazebo::GripMsg&) { return value(); }
};


// service_traits::MD5Sum< ::franka_gripper_gazebo::GripMsgRequest> should match 
// service_traits::MD5Sum< ::franka_gripper_gazebo::GripMsg > 
template<>
struct MD5Sum< ::franka_gripper_gazebo::GripMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_gripper_gazebo::GripMsg >::value();
  }
  static const char* value(const ::franka_gripper_gazebo::GripMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_gripper_gazebo::GripMsgRequest> should match 
// service_traits::DataType< ::franka_gripper_gazebo::GripMsg > 
template<>
struct DataType< ::franka_gripper_gazebo::GripMsgRequest>
{
  static const char* value()
  {
    return DataType< ::franka_gripper_gazebo::GripMsg >::value();
  }
  static const char* value(const ::franka_gripper_gazebo::GripMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_gripper_gazebo::GripMsgResponse> should match 
// service_traits::MD5Sum< ::franka_gripper_gazebo::GripMsg > 
template<>
struct MD5Sum< ::franka_gripper_gazebo::GripMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_gripper_gazebo::GripMsg >::value();
  }
  static const char* value(const ::franka_gripper_gazebo::GripMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_gripper_gazebo::GripMsgResponse> should match 
// service_traits::DataType< ::franka_gripper_gazebo::GripMsg > 
template<>
struct DataType< ::franka_gripper_gazebo::GripMsgResponse>
{
  static const char* value()
  {
    return DataType< ::franka_gripper_gazebo::GripMsg >::value();
  }
  static const char* value(const ::franka_gripper_gazebo::GripMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_GRIPPER_GAZEBO_MESSAGE_GRIPMSG_H
