// Generated by gencpp from file netft_utils/Cancel.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_CANCEL_H
#define NETFT_UTILS_MESSAGE_CANCEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace netft_utils
{
template <class ContainerAllocator>
struct Cancel_
{
  typedef Cancel_<ContainerAllocator> Type;

  Cancel_()
    : toCancel(false)  {
    }
  Cancel_(const ContainerAllocator& _alloc)
    : toCancel(false)  {
  (void)_alloc;
    }



   typedef uint8_t _toCancel_type;
  _toCancel_type toCancel;





  typedef boost::shared_ptr< ::netft_utils::Cancel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::netft_utils::Cancel_<ContainerAllocator> const> ConstPtr;

}; // struct Cancel_

typedef ::netft_utils::Cancel_<std::allocator<void> > Cancel;

typedef boost::shared_ptr< ::netft_utils::Cancel > CancelPtr;
typedef boost::shared_ptr< ::netft_utils::Cancel const> CancelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::netft_utils::Cancel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::netft_utils::Cancel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace netft_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'netft_utils': ['/home/agandhi2/mer_lab/ros_ws/src/projects/piercing_experiments/netft_utils/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::Cancel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::Cancel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::Cancel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::Cancel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::Cancel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::Cancel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::netft_utils::Cancel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60c8bbbce9a3c19aed52c3a96b5d87ff";
  }

  static const char* value(const ::netft_utils::Cancel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60c8bbbce9a3c19aULL;
  static const uint64_t static_value2 = 0xed52c3a96b5d87ffULL;
};

template<class ContainerAllocator>
struct DataType< ::netft_utils::Cancel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "netft_utils/Cancel";
  }

  static const char* value(const ::netft_utils::Cancel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::netft_utils::Cancel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool toCancel\n\
";
  }

  static const char* value(const ::netft_utils::Cancel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::netft_utils::Cancel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toCancel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cancel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::netft_utils::Cancel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::netft_utils::Cancel_<ContainerAllocator>& v)
  {
    s << indent << "toCancel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.toCancel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_CANCEL_H
