// Generated by gencpp from file netft_utils/SetBias.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_SETBIAS_H
#define NETFT_UTILS_MESSAGE_SETBIAS_H

#include <ros/service_traits.h>


#include <netft_utils/SetBiasRequest.h>
#include <netft_utils/SetBiasResponse.h>


namespace netft_utils
{

struct SetBias
{

typedef SetBiasRequest Request;
typedef SetBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBias
} // namespace netft_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::netft_utils::SetBias > {
  static const char* value()
  {
    return "24c559ab4eda1111c9526db57ba60c9c";
  }

  static const char* value(const ::netft_utils::SetBias&) { return value(); }
};

template<>
struct DataType< ::netft_utils::SetBias > {
  static const char* value()
  {
    return "netft_utils/SetBias";
  }

  static const char* value(const ::netft_utils::SetBias&) { return value(); }
};


// service_traits::MD5Sum< ::netft_utils::SetBiasRequest> should match 
// service_traits::MD5Sum< ::netft_utils::SetBias > 
template<>
struct MD5Sum< ::netft_utils::SetBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::netft_utils::SetBias >::value();
  }
  static const char* value(const ::netft_utils::SetBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::netft_utils::SetBiasRequest> should match 
// service_traits::DataType< ::netft_utils::SetBias > 
template<>
struct DataType< ::netft_utils::SetBiasRequest>
{
  static const char* value()
  {
    return DataType< ::netft_utils::SetBias >::value();
  }
  static const char* value(const ::netft_utils::SetBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::netft_utils::SetBiasResponse> should match 
// service_traits::MD5Sum< ::netft_utils::SetBias > 
template<>
struct MD5Sum< ::netft_utils::SetBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::netft_utils::SetBias >::value();
  }
  static const char* value(const ::netft_utils::SetBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::netft_utils::SetBiasResponse> should match 
// service_traits::DataType< ::netft_utils::SetBias > 
template<>
struct DataType< ::netft_utils::SetBiasResponse>
{
  static const char* value()
  {
    return DataType< ::netft_utils::SetBias >::value();
  }
  static const char* value(const ::netft_utils::SetBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_SETBIAS_H
