// Generated by gencpp from file netft_utils/SetBiasRequest.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_SETBIASREQUEST_H
#define NETFT_UTILS_MESSAGE_SETBIASREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace netft_utils
{
template <class ContainerAllocator>
struct SetBiasRequest_
{
  typedef SetBiasRequest_<ContainerAllocator> Type;

  SetBiasRequest_()
    : toBias(false)
    , forceMax(0.0)
    , torqueMax(0.0)  {
    }
  SetBiasRequest_(const ContainerAllocator& _alloc)
    : toBias(false)
    , forceMax(0.0)
    , torqueMax(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _toBias_type;
  _toBias_type toBias;

   typedef double _forceMax_type;
  _forceMax_type forceMax;

   typedef double _torqueMax_type;
  _torqueMax_type torqueMax;





  typedef boost::shared_ptr< ::netft_utils::SetBiasRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::netft_utils::SetBiasRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBiasRequest_

typedef ::netft_utils::SetBiasRequest_<std::allocator<void> > SetBiasRequest;

typedef boost::shared_ptr< ::netft_utils::SetBiasRequest > SetBiasRequestPtr;
typedef boost::shared_ptr< ::netft_utils::SetBiasRequest const> SetBiasRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::netft_utils::SetBiasRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::netft_utils::SetBiasRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace netft_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'netft_utils': ['/home/agandhi2/mer_lab/ros_ws/src/projects/piercing_experiments/netft_utils/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetBiasRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetBiasRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetBiasRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b52f3420f4c01edd09841826073309b3";
  }

  static const char* value(const ::netft_utils::SetBiasRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb52f3420f4c01eddULL;
  static const uint64_t static_value2 = 0x09841826073309b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "netft_utils/SetBiasRequest";
  }

  static const char* value(const ::netft_utils::SetBiasRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool toBias\n\
float64 forceMax\n\
float64 torqueMax\n\
";
  }

  static const char* value(const ::netft_utils::SetBiasRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toBias);
      stream.next(m.forceMax);
      stream.next(m.torqueMax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBiasRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::netft_utils::SetBiasRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::netft_utils::SetBiasRequest_<ContainerAllocator>& v)
  {
    s << indent << "toBias: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.toBias);
    s << indent << "forceMax: ";
    Printer<double>::stream(s, indent + "  ", v.forceMax);
    s << indent << "torqueMax: ";
    Printer<double>::stream(s, indent + "  ", v.torqueMax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_SETBIASREQUEST_H
