// Generated by gencpp from file netft_utils/SetFilterRequest.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_SETFILTERREQUEST_H
#define NETFT_UTILS_MESSAGE_SETFILTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace netft_utils
{
template <class ContainerAllocator>
struct SetFilterRequest_
{
  typedef SetFilterRequest_<ContainerAllocator> Type;

  SetFilterRequest_()
    : toFilter(false)
    , deltaT(0.0)
    , cutoffFrequency(0.0)  {
    }
  SetFilterRequest_(const ContainerAllocator& _alloc)
    : toFilter(false)
    , deltaT(0.0)
    , cutoffFrequency(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _toFilter_type;
  _toFilter_type toFilter;

   typedef double _deltaT_type;
  _deltaT_type deltaT;

   typedef double _cutoffFrequency_type;
  _cutoffFrequency_type cutoffFrequency;





  typedef boost::shared_ptr< ::netft_utils::SetFilterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::netft_utils::SetFilterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFilterRequest_

typedef ::netft_utils::SetFilterRequest_<std::allocator<void> > SetFilterRequest;

typedef boost::shared_ptr< ::netft_utils::SetFilterRequest > SetFilterRequestPtr;
typedef boost::shared_ptr< ::netft_utils::SetFilterRequest const> SetFilterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::netft_utils::SetFilterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::netft_utils::SetFilterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace netft_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'netft_utils': ['/home/agandhi2/mer_lab/ros_ws/src/projects/piercing_experiments/netft_utils/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetFilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetFilterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetFilterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63edfd1498649d874534855980e23bf0";
  }

  static const char* value(const ::netft_utils::SetFilterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63edfd1498649d87ULL;
  static const uint64_t static_value2 = 0x4534855980e23bf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "netft_utils/SetFilterRequest";
  }

  static const char* value(const ::netft_utils::SetFilterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool toFilter\n\
float64 deltaT\n\
float64 cutoffFrequency\n\
";
  }

  static const char* value(const ::netft_utils::SetFilterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toFilter);
      stream.next(m.deltaT);
      stream.next(m.cutoffFrequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFilterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::netft_utils::SetFilterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::netft_utils::SetFilterRequest_<ContainerAllocator>& v)
  {
    s << indent << "toFilter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.toFilter);
    s << indent << "deltaT: ";
    Printer<double>::stream(s, indent + "  ", v.deltaT);
    s << indent << "cutoffFrequency: ";
    Printer<double>::stream(s, indent + "  ", v.cutoffFrequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_SETFILTERREQUEST_H
