// Generated by gencpp from file netft_utils/SetThresholdRequest.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_SETTHRESHOLDREQUEST_H
#define NETFT_UTILS_MESSAGE_SETTHRESHOLDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/WrenchStamped.h>

namespace netft_utils
{
template <class ContainerAllocator>
struct SetThresholdRequest_
{
  typedef SetThresholdRequest_<ContainerAllocator> Type;

  SetThresholdRequest_()
    : data()  {
    }
  SetThresholdRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::WrenchStamped_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::netft_utils::SetThresholdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::netft_utils::SetThresholdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetThresholdRequest_

typedef ::netft_utils::SetThresholdRequest_<std::allocator<void> > SetThresholdRequest;

typedef boost::shared_ptr< ::netft_utils::SetThresholdRequest > SetThresholdRequestPtr;
typedef boost::shared_ptr< ::netft_utils::SetThresholdRequest const> SetThresholdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::netft_utils::SetThresholdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace netft_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'netft_utils': ['/home/agandhi2/mer_lab/ros_ws/src/projects/piercing_experiments/netft_utils/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::netft_utils::SetThresholdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::netft_utils::SetThresholdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::netft_utils::SetThresholdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fd23f6c9d59d629e282cea12d1b5f80";
  }

  static const char* value(const ::netft_utils::SetThresholdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fd23f6c9d59d629ULL;
  static const uint64_t static_value2 = 0xe282cea12d1b5f80ULL;
};

template<class ContainerAllocator>
struct DataType< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "netft_utils/SetThresholdRequest";
  }

  static const char* value(const ::netft_utils::SetThresholdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/WrenchStamped data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/WrenchStamped\n\
# A wrench with reference coordinate frame and timestamp\n\
Header header\n\
Wrench wrench\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, separated into\n\
# its linear and angular parts.\n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::netft_utils::SetThresholdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetThresholdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::netft_utils::SetThresholdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::netft_utils::SetThresholdRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_SETTHRESHOLDREQUEST_H
