// Generated by gencpp from file netft_utils/StartSim.msg
// DO NOT EDIT!


#ifndef NETFT_UTILS_MESSAGE_STARTSIM_H
#define NETFT_UTILS_MESSAGE_STARTSIM_H

#include <ros/service_traits.h>


#include <netft_utils/StartSimRequest.h>
#include <netft_utils/StartSimResponse.h>


namespace netft_utils
{

struct StartSim
{

typedef StartSimRequest Request;
typedef StartSimResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartSim
} // namespace netft_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::netft_utils::StartSim > {
  static const char* value()
  {
    return "f9bc0ea45e890996bb2e2ce115e7c8c3";
  }

  static const char* value(const ::netft_utils::StartSim&) { return value(); }
};

template<>
struct DataType< ::netft_utils::StartSim > {
  static const char* value()
  {
    return "netft_utils/StartSim";
  }

  static const char* value(const ::netft_utils::StartSim&) { return value(); }
};


// service_traits::MD5Sum< ::netft_utils::StartSimRequest> should match 
// service_traits::MD5Sum< ::netft_utils::StartSim > 
template<>
struct MD5Sum< ::netft_utils::StartSimRequest>
{
  static const char* value()
  {
    return MD5Sum< ::netft_utils::StartSim >::value();
  }
  static const char* value(const ::netft_utils::StartSimRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::netft_utils::StartSimRequest> should match 
// service_traits::DataType< ::netft_utils::StartSim > 
template<>
struct DataType< ::netft_utils::StartSimRequest>
{
  static const char* value()
  {
    return DataType< ::netft_utils::StartSim >::value();
  }
  static const char* value(const ::netft_utils::StartSimRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::netft_utils::StartSimResponse> should match 
// service_traits::MD5Sum< ::netft_utils::StartSim > 
template<>
struct MD5Sum< ::netft_utils::StartSimResponse>
{
  static const char* value()
  {
    return MD5Sum< ::netft_utils::StartSim >::value();
  }
  static const char* value(const ::netft_utils::StartSimResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::netft_utils::StartSimResponse> should match 
// service_traits::DataType< ::netft_utils::StartSim > 
template<>
struct DataType< ::netft_utils::StartSimResponse>
{
  static const char* value()
  {
    return DataType< ::netft_utils::StartSim >::value();
  }
  static const char* value(const ::netft_utils::StartSimResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETFT_UTILS_MESSAGE_STARTSIM_H
