// Generated by gencpp from file assist_feeding/finger_orientationRequest.msg
// DO NOT EDIT!


#ifndef ASSIST_FEEDING_MESSAGE_FINGER_ORIENTATIONREQUEST_H
#define ASSIST_FEEDING_MESSAGE_FINGER_ORIENTATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assist_feeding
{
template <class ContainerAllocator>
struct finger_orientationRequest_
{
  typedef finger_orientationRequest_<ContainerAllocator> Type;

  finger_orientationRequest_()
    : finger_angle(0.0)  {
    }
  finger_orientationRequest_(const ContainerAllocator& _alloc)
    : finger_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _finger_angle_type;
  _finger_angle_type finger_angle;





  typedef boost::shared_ptr< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct finger_orientationRequest_

typedef ::assist_feeding::finger_orientationRequest_<std::allocator<void> > finger_orientationRequest;

typedef boost::shared_ptr< ::assist_feeding::finger_orientationRequest > finger_orientationRequestPtr;
typedef boost::shared_ptr< ::assist_feeding::finger_orientationRequest const> finger_orientationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assist_feeding::finger_orientationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assist_feeding

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2649f48d233c8c347b13cd50f5edf8d2";
  }

  static const char* value(const ::assist_feeding::finger_orientationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2649f48d233c8c34ULL;
  static const uint64_t static_value2 = 0x7b13cd50f5edf8d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assist_feeding/finger_orientationRequest";
  }

  static const char* value(const ::assist_feeding::finger_orientationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 finger_angle\n\
";
  }

  static const char* value(const ::assist_feeding::finger_orientationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finger_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct finger_orientationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assist_feeding::finger_orientationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assist_feeding::finger_orientationRequest_<ContainerAllocator>& v)
  {
    s << indent << "finger_angle: ";
    Printer<double>::stream(s, indent + "  ", v.finger_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIST_FEEDING_MESSAGE_FINGER_ORIENTATIONREQUEST_H
