// Generated by gencpp from file assist_feeding/gripper_closeRequest.msg
// DO NOT EDIT!


#ifndef ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSEREQUEST_H
#define ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assist_feeding
{
template <class ContainerAllocator>
struct gripper_closeRequest_
{
  typedef gripper_closeRequest_<ContainerAllocator> Type;

  gripper_closeRequest_()
    : gripper_state(0)  {
    }
  gripper_closeRequest_(const ContainerAllocator& _alloc)
    : gripper_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _gripper_state_type;
  _gripper_state_type gripper_state;





  typedef boost::shared_ptr< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_closeRequest_

typedef ::assist_feeding::gripper_closeRequest_<std::allocator<void> > gripper_closeRequest;

typedef boost::shared_ptr< ::assist_feeding::gripper_closeRequest > gripper_closeRequestPtr;
typedef boost::shared_ptr< ::assist_feeding::gripper_closeRequest const> gripper_closeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assist_feeding::gripper_closeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assist_feeding

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3ad4d90dfcecae67a49b86edd9c7af";
  }

  static const char* value(const ::assist_feeding::gripper_closeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3ad4d90dfcecaeULL;
  static const uint64_t static_value2 = 0x67a49b86edd9c7afULL;
};

template<class ContainerAllocator>
struct DataType< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assist_feeding/gripper_closeRequest";
  }

  static const char* value(const ::assist_feeding::gripper_closeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 gripper_state\n\
";
  }

  static const char* value(const ::assist_feeding::gripper_closeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripper_closeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assist_feeding::gripper_closeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assist_feeding::gripper_closeRequest_<ContainerAllocator>& v)
  {
    s << indent << "gripper_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSEREQUEST_H
