// Generated by gencpp from file assist_feeding/gripper_close.msg
// DO NOT EDIT!


#ifndef ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSE_H
#define ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSE_H

#include <ros/service_traits.h>


#include <assist_feeding/gripper_closeRequest.h>
#include <assist_feeding/gripper_closeResponse.h>


namespace assist_feeding
{

struct gripper_close
{

typedef gripper_closeRequest Request;
typedef gripper_closeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gripper_close
} // namespace assist_feeding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assist_feeding::gripper_close > {
  static const char* value()
  {
    return "7626e2955bd6177e24f663e9b9a1fde1";
  }

  static const char* value(const ::assist_feeding::gripper_close&) { return value(); }
};

template<>
struct DataType< ::assist_feeding::gripper_close > {
  static const char* value()
  {
    return "assist_feeding/gripper_close";
  }

  static const char* value(const ::assist_feeding::gripper_close&) { return value(); }
};


// service_traits::MD5Sum< ::assist_feeding::gripper_closeRequest> should match 
// service_traits::MD5Sum< ::assist_feeding::gripper_close > 
template<>
struct MD5Sum< ::assist_feeding::gripper_closeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assist_feeding::gripper_close >::value();
  }
  static const char* value(const ::assist_feeding::gripper_closeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assist_feeding::gripper_closeRequest> should match 
// service_traits::DataType< ::assist_feeding::gripper_close > 
template<>
struct DataType< ::assist_feeding::gripper_closeRequest>
{
  static const char* value()
  {
    return DataType< ::assist_feeding::gripper_close >::value();
  }
  static const char* value(const ::assist_feeding::gripper_closeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assist_feeding::gripper_closeResponse> should match 
// service_traits::MD5Sum< ::assist_feeding::gripper_close > 
template<>
struct MD5Sum< ::assist_feeding::gripper_closeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assist_feeding::gripper_close >::value();
  }
  static const char* value(const ::assist_feeding::gripper_closeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assist_feeding::gripper_closeResponse> should match 
// service_traits::DataType< ::assist_feeding::gripper_close > 
template<>
struct DataType< ::assist_feeding::gripper_closeResponse>
{
  static const char* value()
  {
    return DataType< ::assist_feeding::gripper_close >::value();
  }
  static const char* value(const ::assist_feeding::gripper_closeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIST_FEEDING_MESSAGE_GRIPPER_CLOSE_H
