// Generated by gencpp from file assist_feeding/gripper_open.msg
// DO NOT EDIT!


#ifndef ASSIST_FEEDING_MESSAGE_GRIPPER_OPEN_H
#define ASSIST_FEEDING_MESSAGE_GRIPPER_OPEN_H

#include <ros/service_traits.h>


#include <assist_feeding/gripper_openRequest.h>
#include <assist_feeding/gripper_openResponse.h>


namespace assist_feeding
{

struct gripper_open
{

typedef gripper_openRequest Request;
typedef gripper_openResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gripper_open
} // namespace assist_feeding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assist_feeding::gripper_open > {
  static const char* value()
  {
    return "7626e2955bd6177e24f663e9b9a1fde1";
  }

  static const char* value(const ::assist_feeding::gripper_open&) { return value(); }
};

template<>
struct DataType< ::assist_feeding::gripper_open > {
  static const char* value()
  {
    return "assist_feeding/gripper_open";
  }

  static const char* value(const ::assist_feeding::gripper_open&) { return value(); }
};


// service_traits::MD5Sum< ::assist_feeding::gripper_openRequest> should match 
// service_traits::MD5Sum< ::assist_feeding::gripper_open > 
template<>
struct MD5Sum< ::assist_feeding::gripper_openRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assist_feeding::gripper_open >::value();
  }
  static const char* value(const ::assist_feeding::gripper_openRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assist_feeding::gripper_openRequest> should match 
// service_traits::DataType< ::assist_feeding::gripper_open > 
template<>
struct DataType< ::assist_feeding::gripper_openRequest>
{
  static const char* value()
  {
    return DataType< ::assist_feeding::gripper_open >::value();
  }
  static const char* value(const ::assist_feeding::gripper_openRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assist_feeding::gripper_openResponse> should match 
// service_traits::MD5Sum< ::assist_feeding::gripper_open > 
template<>
struct MD5Sum< ::assist_feeding::gripper_openResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assist_feeding::gripper_open >::value();
  }
  static const char* value(const ::assist_feeding::gripper_openResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assist_feeding::gripper_openResponse> should match 
// service_traits::DataType< ::assist_feeding::gripper_open > 
template<>
struct DataType< ::assist_feeding::gripper_openResponse>
{
  static const char* value()
  {
    return DataType< ::assist_feeding::gripper_open >::value();
  }
  static const char* value(const ::assist_feeding::gripper_openResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIST_FEEDING_MESSAGE_GRIPPER_OPEN_H
