(cl:defpackage assist_feeding-srv
  (:use )
  (:export
   "FINGER_ORIENTATION"
   "<FINGER_ORIENTATION-REQUEST>"
   "FINGER_ORIENTATION-REQUEST"
   "<FINGER_ORIENTATION-RESPONSE>"
   "FINGER_ORIENTATION-RESPONSE"
   "GRIPPER_CLOSE"
   "<GRIPPER_CLOSE-REQUEST>"
   "GRIPPER_CLOSE-REQUEST"
   "<GRIPPER_CLOSE-RESPONSE>"
   "GRIPPER_CLOSE-RESPONSE"
   "GRIPPER_OPEN"
   "<GRIPPER_OPEN-REQUEST>"
   "GRIPPER_OPEN-REQUEST"
   "<GRIPPER_OPEN-RESPONSE>"
   "GRIPPER_OPEN-RESPONSE"
  ))

