panda:
  arm_position_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    gains:
        panda_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
        panda_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
