(cl:defpackage pcl_recorder-srv
  (:use )
  (:export
   "BEGINPOINTCLOUDRANGE"
   "<BEGINPOINTCLOUDRANGE-REQUEST>"
   "BEGINPOINTCLOUDRANGE-REQUEST"
   "<BEGINPOINTCLOUDRANGE-RESPONSE>"
   "BEGINPOINTCLOUDRANGE-RESPONSE"
   "ENDPOINTCLOUDRANGE"
   "<ENDPOINTCLOUDRANGE-REQUEST>"
   "ENDPOINTCLOUDRANGE-REQUEST"
   "<ENDPOINTCLOUDRANGE-RESPONSE>"
   "ENDPOINTCLOUDRANGE-RESPONSE"
   "GETPOINTCLOUD"
   "<GETPOINTCLOUD-REQUEST>"
   "GETPOINTCLOUD-REQUEST"
   "<GETPOINTCLOUD-RESPONSE>"
   "GETPOINTCLOUD-RESPONSE"
  ))

