// Generated by gencpp from file moveit_planner/MoveJointRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEJOINTREQUEST_H
#define MOVEIT_PLANNER_MESSAGE_MOVEJOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_planner
{
template <class ContainerAllocator>
struct MoveJointRequest_
{
  typedef MoveJointRequest_<ContainerAllocator> Type;

  MoveJointRequest_()
    : val()
    , execute(false)  {
    }
  MoveJointRequest_(const ContainerAllocator& _alloc)
    : val(_alloc)
    , execute(false)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _val_type;
  _val_type val;

   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::moveit_planner::MoveJointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_planner::MoveJointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJointRequest_

typedef ::moveit_planner::MoveJointRequest_<std::allocator<void> > MoveJointRequest;

typedef boost::shared_ptr< ::moveit_planner::MoveJointRequest > MoveJointRequestPtr;
typedef boost::shared_ptr< ::moveit_planner::MoveJointRequest const> MoveJointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_planner::MoveJointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::MoveJointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::MoveJointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::MoveJointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c07c95fac99ad0dd277ffa3486c1adc";
  }

  static const char* value(const ::moveit_planner::MoveJointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c07c95fac99ad0dULL;
  static const uint64_t static_value2 = 0xd277ffa3486c1adcULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_planner/MoveJointRequest";
  }

  static const char* value(const ::moveit_planner::MoveJointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] val\n\
bool execute\n\
";
  }

  static const char* value(const ::moveit_planner::MoveJointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_planner::MoveJointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_planner::MoveJointRequest_<ContainerAllocator>& v)
  {
    s << indent << "val[]" << std::endl;
    for (size_t i = 0; i < v.val.size(); ++i)
    {
      s << indent << "  val[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.val[i]);
    }
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEJOINTREQUEST_H
