// Generated by gencpp from file moveit_planner/MovePoint.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEPOINT_H
#define MOVEIT_PLANNER_MESSAGE_MOVEPOINT_H

#include <ros/service_traits.h>


#include <moveit_planner/MovePointRequest.h>
#include <moveit_planner/MovePointResponse.h>


namespace moveit_planner
{

struct MovePoint
{

typedef MovePointRequest Request;
typedef MovePointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePoint
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MovePoint > {
  static const char* value()
  {
    return "09d178cfe7c05e5d8c3ba0747602407a";
  }

  static const char* value(const ::moveit_planner::MovePoint&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MovePoint > {
  static const char* value()
  {
    return "moveit_planner/MovePoint";
  }

  static const char* value(const ::moveit_planner::MovePoint&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MovePointRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MovePoint > 
template<>
struct MD5Sum< ::moveit_planner::MovePointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MovePoint >::value();
  }
  static const char* value(const ::moveit_planner::MovePointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MovePointRequest> should match 
// service_traits::DataType< ::moveit_planner::MovePoint > 
template<>
struct DataType< ::moveit_planner::MovePointRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MovePoint >::value();
  }
  static const char* value(const ::moveit_planner::MovePointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MovePointResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MovePoint > 
template<>
struct MD5Sum< ::moveit_planner::MovePointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MovePoint >::value();
  }
  static const char* value(const ::moveit_planner::MovePointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MovePointResponse> should match 
// service_traits::DataType< ::moveit_planner::MovePoint > 
template<>
struct DataType< ::moveit_planner::MovePointResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MovePoint >::value();
  }
  static const char* value(const ::moveit_planner::MovePointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEPOINT_H
