// Generated by gencpp from file moveit_planner/MovePose.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEPOSE_H
#define MOVEIT_PLANNER_MESSAGE_MOVEPOSE_H

#include <ros/service_traits.h>


#include <moveit_planner/MovePoseRequest.h>
#include <moveit_planner/MovePoseResponse.h>


namespace moveit_planner
{

struct MovePose
{

typedef MovePoseRequest Request;
typedef MovePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePose
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MovePose > {
  static const char* value()
  {
    return "a77c545a10fa137b7b4acf08012288bf";
  }

  static const char* value(const ::moveit_planner::MovePose&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MovePose > {
  static const char* value()
  {
    return "moveit_planner/MovePose";
  }

  static const char* value(const ::moveit_planner::MovePose&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MovePoseRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MovePose > 
template<>
struct MD5Sum< ::moveit_planner::MovePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MovePose >::value();
  }
  static const char* value(const ::moveit_planner::MovePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MovePoseRequest> should match 
// service_traits::DataType< ::moveit_planner::MovePose > 
template<>
struct DataType< ::moveit_planner::MovePoseRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MovePose >::value();
  }
  static const char* value(const ::moveit_planner::MovePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MovePoseResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MovePose > 
template<>
struct MD5Sum< ::moveit_planner::MovePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MovePose >::value();
  }
  static const char* value(const ::moveit_planner::MovePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MovePoseResponse> should match 
// service_traits::DataType< ::moveit_planner::MovePose > 
template<>
struct DataType< ::moveit_planner::MovePoseResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MovePose >::value();
  }
  static const char* value(const ::moveit_planner::MovePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEPOSE_H
