// Generated by gencpp from file moveit_planner/MoveQuat.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEQUAT_H
#define MOVEIT_PLANNER_MESSAGE_MOVEQUAT_H

#include <ros/service_traits.h>


#include <moveit_planner/MoveQuatRequest.h>
#include <moveit_planner/MoveQuatResponse.h>


namespace moveit_planner
{

struct MoveQuat
{

typedef MoveQuatRequest Request;
typedef MoveQuatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveQuat
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MoveQuat > {
  static const char* value()
  {
    return "38b5b4ab2cb69ba284d4cfd4d2765acc";
  }

  static const char* value(const ::moveit_planner::MoveQuat&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MoveQuat > {
  static const char* value()
  {
    return "moveit_planner/MoveQuat";
  }

  static const char* value(const ::moveit_planner::MoveQuat&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MoveQuatRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveQuat > 
template<>
struct MD5Sum< ::moveit_planner::MoveQuatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveQuat >::value();
  }
  static const char* value(const ::moveit_planner::MoveQuatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveQuatRequest> should match 
// service_traits::DataType< ::moveit_planner::MoveQuat > 
template<>
struct DataType< ::moveit_planner::MoveQuatRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveQuat >::value();
  }
  static const char* value(const ::moveit_planner::MoveQuatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MoveQuatResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveQuat > 
template<>
struct MD5Sum< ::moveit_planner::MoveQuatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveQuat >::value();
  }
  static const char* value(const ::moveit_planner::MoveQuatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveQuatResponse> should match 
// service_traits::DataType< ::moveit_planner::MoveQuat > 
template<>
struct DataType< ::moveit_planner::MoveQuatResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveQuat >::value();
  }
  static const char* value(const ::moveit_planner::MoveQuatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEQUAT_H
