// Generated by gencpp from file moveit_planner/MoveJoint.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEJOINT_H
#define MOVEIT_PLANNER_MESSAGE_MOVEJOINT_H

#include <ros/service_traits.h>


#include <moveit_planner/MoveJointRequest.h>
#include <moveit_planner/MoveJointResponse.h>


namespace moveit_planner
{

struct MoveJoint
{

typedef MoveJointRequest Request;
typedef MoveJointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoint
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MoveJoint > {
  static const char* value()
  {
    return "9c07c95fac99ad0dd277ffa3486c1adc";
  }

  static const char* value(const ::moveit_planner::MoveJoint&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MoveJoint > {
  static const char* value()
  {
    return "moveit_planner/MoveJoint";
  }

  static const char* value(const ::moveit_planner::MoveJoint&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MoveJointRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveJoint > 
template<>
struct MD5Sum< ::moveit_planner::MoveJointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveJoint >::value();
  }
  static const char* value(const ::moveit_planner::MoveJointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveJointRequest> should match 
// service_traits::DataType< ::moveit_planner::MoveJoint > 
template<>
struct DataType< ::moveit_planner::MoveJointRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveJoint >::value();
  }
  static const char* value(const ::moveit_planner::MoveJointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MoveJointResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveJoint > 
template<>
struct MD5Sum< ::moveit_planner::MoveJointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveJoint >::value();
  }
  static const char* value(const ::moveit_planner::MoveJointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveJointResponse> should match 
// service_traits::DataType< ::moveit_planner::MoveJoint > 
template<>
struct DataType< ::moveit_planner::MoveJointResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveJoint >::value();
  }
  static const char* value(const ::moveit_planner::MoveJointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEJOINT_H
