// Generated by gencpp from file moveit_planner/MoveAway.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVEAWAY_H
#define MOVEIT_PLANNER_MESSAGE_MOVEAWAY_H

#include <ros/service_traits.h>


#include <moveit_planner/MoveAwayRequest.h>
#include <moveit_planner/MoveAwayResponse.h>


namespace moveit_planner
{

struct MoveAway
{

typedef MoveAwayRequest Request;
typedef MoveAwayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveAway
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MoveAway > {
  static const char* value()
  {
    return "b0b7b3e5a88a68f810ee5cdc3adb57e7";
  }

  static const char* value(const ::moveit_planner::MoveAway&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MoveAway > {
  static const char* value()
  {
    return "moveit_planner/MoveAway";
  }

  static const char* value(const ::moveit_planner::MoveAway&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MoveAwayRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveAway > 
template<>
struct MD5Sum< ::moveit_planner::MoveAwayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveAway >::value();
  }
  static const char* value(const ::moveit_planner::MoveAwayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveAwayRequest> should match 
// service_traits::DataType< ::moveit_planner::MoveAway > 
template<>
struct DataType< ::moveit_planner::MoveAwayRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveAway >::value();
  }
  static const char* value(const ::moveit_planner::MoveAwayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MoveAwayResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveAway > 
template<>
struct MD5Sum< ::moveit_planner::MoveAwayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveAway >::value();
  }
  static const char* value(const ::moveit_planner::MoveAwayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveAwayResponse> should match 
// service_traits::DataType< ::moveit_planner::MoveAway > 
template<>
struct DataType< ::moveit_planner::MoveAwayResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveAway >::value();
  }
  static const char* value(const ::moveit_planner::MoveAwayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVEAWAY_H
