// Generated by gencpp from file moveit_planner/MoveCart.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_MOVECART_H
#define MOVEIT_PLANNER_MESSAGE_MOVECART_H

#include <ros/service_traits.h>


#include <moveit_planner/MoveCartRequest.h>
#include <moveit_planner/MoveCartResponse.h>


namespace moveit_planner
{

struct MoveCart
{

typedef MoveCartRequest Request;
typedef MoveCartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveCart
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::MoveCart > {
  static const char* value()
  {
    return "a77c545a10fa137b7b4acf08012288bf";
  }

  static const char* value(const ::moveit_planner::MoveCart&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::MoveCart > {
  static const char* value()
  {
    return "moveit_planner/MoveCart";
  }

  static const char* value(const ::moveit_planner::MoveCart&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::MoveCartRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveCart > 
template<>
struct MD5Sum< ::moveit_planner::MoveCartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveCart >::value();
  }
  static const char* value(const ::moveit_planner::MoveCartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveCartRequest> should match 
// service_traits::DataType< ::moveit_planner::MoveCart > 
template<>
struct DataType< ::moveit_planner::MoveCartRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveCart >::value();
  }
  static const char* value(const ::moveit_planner::MoveCartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::MoveCartResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::MoveCart > 
template<>
struct MD5Sum< ::moveit_planner::MoveCartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::MoveCart >::value();
  }
  static const char* value(const ::moveit_planner::MoveCartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::MoveCartResponse> should match 
// service_traits::DataType< ::moveit_planner::MoveCart > 
template<>
struct DataType< ::moveit_planner::MoveCartResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::MoveCart >::value();
  }
  static const char* value(const ::moveit_planner::MoveCartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_MOVECART_H
