// Generated by gencpp from file moveit_planner/SetVelocity.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_SETVELOCITY_H
#define MOVEIT_PLANNER_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <moveit_planner/SetVelocityRequest.h>
#include <moveit_planner/SetVelocityResponse.h>


namespace moveit_planner
{

struct SetVelocity
{

typedef SetVelocityRequest Request;
typedef SetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVelocity
} // namespace moveit_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_planner::SetVelocity > {
  static const char* value()
  {
    return "a61a7a7956fba028d52c35ae7e4e38a7";
  }

  static const char* value(const ::moveit_planner::SetVelocity&) { return value(); }
};

template<>
struct DataType< ::moveit_planner::SetVelocity > {
  static const char* value()
  {
    return "moveit_planner/SetVelocity";
  }

  static const char* value(const ::moveit_planner::SetVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_planner::SetVelocityRequest> should match 
// service_traits::MD5Sum< ::moveit_planner::SetVelocity > 
template<>
struct MD5Sum< ::moveit_planner::SetVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::SetVelocity >::value();
  }
  static const char* value(const ::moveit_planner::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::SetVelocityRequest> should match 
// service_traits::DataType< ::moveit_planner::SetVelocity > 
template<>
struct DataType< ::moveit_planner::SetVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::SetVelocity >::value();
  }
  static const char* value(const ::moveit_planner::SetVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_planner::SetVelocityResponse> should match 
// service_traits::MD5Sum< ::moveit_planner::SetVelocity > 
template<>
struct MD5Sum< ::moveit_planner::SetVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_planner::SetVelocity >::value();
  }
  static const char* value(const ::moveit_planner::SetVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_planner::SetVelocityResponse> should match 
// service_traits::DataType< ::moveit_planner::SetVelocity > 
template<>
struct DataType< ::moveit_planner::SetVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_planner::SetVelocity >::value();
  }
  static const char* value(const ::moveit_planner::SetVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_SETVELOCITY_H
