// Generated by gencpp from file moveit_planner/SetVelocityResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_SETVELOCITYRESPONSE_H
#define MOVEIT_PLANNER_MESSAGE_SETVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_planner
{
template <class ContainerAllocator>
struct SetVelocityResponse_
{
  typedef SetVelocityResponse_<ContainerAllocator> Type;

  SetVelocityResponse_()
    {
    }
  SetVelocityResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityResponse_

typedef ::moveit_planner::SetVelocityResponse_<std::allocator<void> > SetVelocityResponse;

typedef boost::shared_ptr< ::moveit_planner::SetVelocityResponse > SetVelocityResponsePtr;
typedef boost::shared_ptr< ::moveit_planner::SetVelocityResponse const> SetVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_planner::SetVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::moveit_planner::SetVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_planner/SetVelocityResponse";
  }

  static const char* value(const ::moveit_planner::SetVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::moveit_planner::SetVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_planner::SetVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::moveit_planner::SetVelocityResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_SETVELOCITYRESPONSE_H
