// Generated by gencpp from file moveit_planner/SetVelocityRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_PLANNER_MESSAGE_SETVELOCITYREQUEST_H
#define MOVEIT_PLANNER_MESSAGE_SETVELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_planner
{
template <class ContainerAllocator>
struct SetVelocityRequest_
{
  typedef SetVelocityRequest_<ContainerAllocator> Type;

  SetVelocityRequest_()
    : velScaling(0.0)  {
    }
  SetVelocityRequest_(const ContainerAllocator& _alloc)
    : velScaling(0.0)  {
  (void)_alloc;
    }



   typedef double _velScaling_type;
  _velScaling_type velScaling;





  typedef boost::shared_ptr< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocityRequest_

typedef ::moveit_planner::SetVelocityRequest_<std::allocator<void> > SetVelocityRequest;

typedef boost::shared_ptr< ::moveit_planner::SetVelocityRequest > SetVelocityRequestPtr;
typedef boost::shared_ptr< ::moveit_planner::SetVelocityRequest const> SetVelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_planner::SetVelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveit_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a61a7a7956fba028d52c35ae7e4e38a7";
  }

  static const char* value(const ::moveit_planner::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa61a7a7956fba028ULL;
  static const uint64_t static_value2 = 0xd52c35ae7e4e38a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_planner/SetVelocityRequest";
  }

  static const char* value(const ::moveit_planner::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 velScaling\n\
";
  }

  static const char* value(const ::moveit_planner::SetVelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velScaling);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_planner::SetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_planner::SetVelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "velScaling: ";
    Printer<double>::stream(s, indent + "  ", v.velScaling);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_PLANNER_MESSAGE_SETVELOCITYREQUEST_H
