// Generated by gencpp from file randomizer/RandRequest.msg
// DO NOT EDIT!


#ifndef RANDOMIZER_MESSAGE_RANDREQUEST_H
#define RANDOMIZER_MESSAGE_RANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace randomizer
{
template <class ContainerAllocator>
struct RandRequest_
{
  typedef RandRequest_<ContainerAllocator> Type;

  RandRequest_()
    : toStart(false)  {
    }
  RandRequest_(const ContainerAllocator& _alloc)
    : toStart(false)  {
  (void)_alloc;
    }



   typedef uint8_t _toStart_type;
  _toStart_type toStart;





  typedef boost::shared_ptr< ::randomizer::RandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::randomizer::RandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RandRequest_

typedef ::randomizer::RandRequest_<std::allocator<void> > RandRequest;

typedef boost::shared_ptr< ::randomizer::RandRequest > RandRequestPtr;
typedef boost::shared_ptr< ::randomizer::RandRequest const> RandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::randomizer::RandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::randomizer::RandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace randomizer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::randomizer::RandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::randomizer::RandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomizer::RandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomizer::RandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomizer::RandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomizer::RandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::randomizer::RandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb0da9f8cfc2a14ca80d5a9fa236c5fd";
  }

  static const char* value(const ::randomizer::RandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb0da9f8cfc2a14cULL;
  static const uint64_t static_value2 = 0xa80d5a9fa236c5fdULL;
};

template<class ContainerAllocator>
struct DataType< ::randomizer::RandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "randomizer/RandRequest";
  }

  static const char* value(const ::randomizer::RandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::randomizer::RandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool toStart\n\
";
  }

  static const char* value(const ::randomizer::RandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::randomizer::RandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toStart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::randomizer::RandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::randomizer::RandRequest_<ContainerAllocator>& v)
  {
    s << indent << "toStart: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.toStart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANDOMIZER_MESSAGE_RANDREQUEST_H
