model {
  file: "model.sdf"
}
name: "Cole_Hardware_Bowl_Scirocco_YellowBlue"
description: "Cole Hardware Bowl Scirocco, Yellow/Blue"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Cole Hardware"
}
annotations {
  key: "gtin"
  value: "00064180220672"
}
annotations {
  key: "sku"
  value: "00064180220672"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
