// Generated by gencpp from file pcl_recorder/BeginPointCloudRangeResponse.msg
// DO NOT EDIT!


#ifndef PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGERESPONSE_H
#define PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_recorder
{
template <class ContainerAllocator>
struct BeginPointCloudRangeResponse_
{
  typedef BeginPointCloudRangeResponse_<ContainerAllocator> Type;

  BeginPointCloudRangeResponse_()
    : limitSeconds(0.0)  {
    }
  BeginPointCloudRangeResponse_(const ContainerAllocator& _alloc)
    : limitSeconds(0.0)  {
  (void)_alloc;
    }



   typedef double _limitSeconds_type;
  _limitSeconds_type limitSeconds;





  typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BeginPointCloudRangeResponse_

typedef ::pcl_recorder::BeginPointCloudRangeResponse_<std::allocator<void> > BeginPointCloudRangeResponse;

typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeResponse > BeginPointCloudRangeResponsePtr;
typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeResponse const> BeginPointCloudRangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pcl_recorder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9311910f05228bb5cc6df433181f77e3";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9311910f05228bb5ULL;
  static const uint64_t static_value2 = 0xcc6df433181f77e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_recorder/BeginPointCloudRangeResponse";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 limitSeconds\n\
";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limitSeconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BeginPointCloudRangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_recorder::BeginPointCloudRangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "limitSeconds: ";
    Printer<double>::stream(s, indent + "  ", v.limitSeconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGERESPONSE_H
