// Generated by gencpp from file pcl_recorder/BeginPointCloudRange.msg
// DO NOT EDIT!


#ifndef PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGE_H
#define PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGE_H

#include <ros/service_traits.h>


#include <pcl_recorder/BeginPointCloudRangeRequest.h>
#include <pcl_recorder/BeginPointCloudRangeResponse.h>


namespace pcl_recorder
{

struct BeginPointCloudRange
{

typedef BeginPointCloudRangeRequest Request;
typedef BeginPointCloudRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BeginPointCloudRange
} // namespace pcl_recorder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_recorder::BeginPointCloudRange > {
  static const char* value()
  {
    return "10432e08567eb968c3444f0fa65097b5";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRange&) { return value(); }
};

template<>
struct DataType< ::pcl_recorder::BeginPointCloudRange > {
  static const char* value()
  {
    return "pcl_recorder/BeginPointCloudRange";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRange&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_recorder::BeginPointCloudRangeRequest> should match 
// service_traits::MD5Sum< ::pcl_recorder::BeginPointCloudRange > 
template<>
struct MD5Sum< ::pcl_recorder::BeginPointCloudRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::BeginPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::BeginPointCloudRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::BeginPointCloudRangeRequest> should match 
// service_traits::DataType< ::pcl_recorder::BeginPointCloudRange > 
template<>
struct DataType< ::pcl_recorder::BeginPointCloudRangeRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::BeginPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::BeginPointCloudRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_recorder::BeginPointCloudRangeResponse> should match 
// service_traits::MD5Sum< ::pcl_recorder::BeginPointCloudRange > 
template<>
struct MD5Sum< ::pcl_recorder::BeginPointCloudRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::BeginPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::BeginPointCloudRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::BeginPointCloudRangeResponse> should match 
// service_traits::DataType< ::pcl_recorder::BeginPointCloudRange > 
template<>
struct DataType< ::pcl_recorder::BeginPointCloudRangeResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::BeginPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::BeginPointCloudRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGE_H
