// Generated by gencpp from file pcl_recorder/BeginPointCloudRangeRequest.msg
// DO NOT EDIT!


#ifndef PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGEREQUEST_H
#define PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcl_recorder
{
template <class ContainerAllocator>
struct BeginPointCloudRangeRequest_
{
  typedef BeginPointCloudRangeRequest_<ContainerAllocator> Type;

  BeginPointCloudRangeRequest_()
    : frequency(0.0)  {
    }
  BeginPointCloudRangeRequest_(const ContainerAllocator& _alloc)
    : frequency(0.0)  {
  (void)_alloc;
    }



   typedef double _frequency_type;
  _frequency_type frequency;





  typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BeginPointCloudRangeRequest_

typedef ::pcl_recorder::BeginPointCloudRangeRequest_<std::allocator<void> > BeginPointCloudRangeRequest;

typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeRequest > BeginPointCloudRangeRequestPtr;
typedef boost::shared_ptr< ::pcl_recorder::BeginPointCloudRangeRequest const> BeginPointCloudRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pcl_recorder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49c627ecd142a5c42775297233551ead";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49c627ecd142a5c4ULL;
  static const uint64_t static_value2 = 0x2775297233551eadULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_recorder/BeginPointCloudRangeRequest";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 frequency\n\
";
  }

  static const char* value(const ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BeginPointCloudRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_recorder::BeginPointCloudRangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_RECORDER_MESSAGE_BEGINPOINTCLOUDRANGEREQUEST_H
