// Generated by gencpp from file pcl_recorder/EndPointCloudRange.msg
// DO NOT EDIT!


#ifndef PCL_RECORDER_MESSAGE_ENDPOINTCLOUDRANGE_H
#define PCL_RECORDER_MESSAGE_ENDPOINTCLOUDRANGE_H

#include <ros/service_traits.h>


#include <pcl_recorder/EndPointCloudRangeRequest.h>
#include <pcl_recorder/EndPointCloudRangeResponse.h>


namespace pcl_recorder
{

struct EndPointCloudRange
{

typedef EndPointCloudRangeRequest Request;
typedef EndPointCloudRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EndPointCloudRange
} // namespace pcl_recorder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_recorder::EndPointCloudRange > {
  static const char* value()
  {
    return "36ef54ba68cfe88c3625117f7de48f46";
  }

  static const char* value(const ::pcl_recorder::EndPointCloudRange&) { return value(); }
};

template<>
struct DataType< ::pcl_recorder::EndPointCloudRange > {
  static const char* value()
  {
    return "pcl_recorder/EndPointCloudRange";
  }

  static const char* value(const ::pcl_recorder::EndPointCloudRange&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_recorder::EndPointCloudRangeRequest> should match 
// service_traits::MD5Sum< ::pcl_recorder::EndPointCloudRange > 
template<>
struct MD5Sum< ::pcl_recorder::EndPointCloudRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::EndPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::EndPointCloudRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::EndPointCloudRangeRequest> should match 
// service_traits::DataType< ::pcl_recorder::EndPointCloudRange > 
template<>
struct DataType< ::pcl_recorder::EndPointCloudRangeRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::EndPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::EndPointCloudRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_recorder::EndPointCloudRangeResponse> should match 
// service_traits::MD5Sum< ::pcl_recorder::EndPointCloudRange > 
template<>
struct MD5Sum< ::pcl_recorder::EndPointCloudRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::EndPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::EndPointCloudRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::EndPointCloudRangeResponse> should match 
// service_traits::DataType< ::pcl_recorder::EndPointCloudRange > 
template<>
struct DataType< ::pcl_recorder::EndPointCloudRangeResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::EndPointCloudRange >::value();
  }
  static const char* value(const ::pcl_recorder::EndPointCloudRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_RECORDER_MESSAGE_ENDPOINTCLOUDRANGE_H
