// Generated by gencpp from file pcl_recorder/GetPointCloud.msg
// DO NOT EDIT!


#ifndef PCL_RECORDER_MESSAGE_GETPOINTCLOUD_H
#define PCL_RECORDER_MESSAGE_GETPOINTCLOUD_H

#include <ros/service_traits.h>


#include <pcl_recorder/GetPointCloudRequest.h>
#include <pcl_recorder/GetPointCloudResponse.h>


namespace pcl_recorder
{

struct GetPointCloud
{

typedef GetPointCloudRequest Request;
typedef GetPointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPointCloud
} // namespace pcl_recorder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_recorder::GetPointCloud > {
  static const char* value()
  {
    return "d5d036aeaa020e7f5e0ddd6aeae0e7d8";
  }

  static const char* value(const ::pcl_recorder::GetPointCloud&) { return value(); }
};

template<>
struct DataType< ::pcl_recorder::GetPointCloud > {
  static const char* value()
  {
    return "pcl_recorder/GetPointCloud";
  }

  static const char* value(const ::pcl_recorder::GetPointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_recorder::GetPointCloudRequest> should match 
// service_traits::MD5Sum< ::pcl_recorder::GetPointCloud > 
template<>
struct MD5Sum< ::pcl_recorder::GetPointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::GetPointCloud >::value();
  }
  static const char* value(const ::pcl_recorder::GetPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::GetPointCloudRequest> should match 
// service_traits::DataType< ::pcl_recorder::GetPointCloud > 
template<>
struct DataType< ::pcl_recorder::GetPointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::GetPointCloud >::value();
  }
  static const char* value(const ::pcl_recorder::GetPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_recorder::GetPointCloudResponse> should match 
// service_traits::MD5Sum< ::pcl_recorder::GetPointCloud > 
template<>
struct MD5Sum< ::pcl_recorder::GetPointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_recorder::GetPointCloud >::value();
  }
  static const char* value(const ::pcl_recorder::GetPointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_recorder::GetPointCloudResponse> should match 
// service_traits::DataType< ::pcl_recorder::GetPointCloud > 
template<>
struct DataType< ::pcl_recorder::GetPointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_recorder::GetPointCloud >::value();
  }
  static const char* value(const ::pcl_recorder::GetPointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_RECORDER_MESSAGE_GETPOINTCLOUD_H
