# Parameters with for the objects used

objectsInfo: {
  nObjects: 22,
  ID1: {
    Filename: prismAV6x6x6,
    Description: Prism 6x6x6,
    nPoses: 1,
    Pose1: [0.050,0.000,0.000,0,89],
  },
  ID2: {
    Filename: prismAV10x8x4,
    Description: Prism 10x8x4,
    nPoses: 2,
    Pose1: [0.060,1.570,0.000,0,179],
    Pose2: [0.070,1.570,1.570,0,179],
  },
  ID3: {
    Filename: prismAV20x6x5,
    Description: Prism 20x6x5,
    nPoses: 3,
    Pose1: [0.040,0.000,0.000,0,179],
    Pose2: [0.050,1.570,0.000,0,179],
    Pose3: [0.120,1.570,1.570,0,179],
  },
  ID4: {
    Filename: bowl2AV,
    Description: Bowl,
    nPoses: 1,
    Pose1: [0.015,0.000,0.000,0,1],
  },
  ID5: {
    Filename: cinderBlockAV,
    Description: Cinder Block,
    nPoses: 1,
    Pose1: [0.015,0.000,0.000,0,89],
  },
  ID6: {
    Filename: handleAV,
    Description: Door Handle,
    nPoses: 1,
    Pose1: [0.015,0.000,0.000,0,359],
  },
  ID7: {
    Filename: gasketAV,
    Description: Gasket,
    nPoses: 1,
    Pose1: [0.015,0.000,0.000,0,179],
  },
  ID8: {
    Filename: drillAV,
    Description: Cordless Drill,
    nPoses: 7,
    Pose1: [0.012,0.000,0.000,0,359],
    Pose2: [0.084,1.459,-0.751,0,359],
    Pose3: [0.082,1.398,-0.014,0,359],
    Pose4: [0.040,0.280,-1.040,0,359],
    Pose5: [0.249,2.860,-0.400,0,359],
    Pose6: [0.068,-1.287,-0.477,0,359],
    Pose7: [0.048,-1.570,1.480,0,359],
  },
  ID9: {
    Filename: cupAV,
    Description: Tea Cup,
    nPoses: 1,
    Pose1: [0.015,0.000,0.000,0,359],
  },
  ID10: {
    Filename: sprayFlaskAV,
    Description: Spray Flask,
    nPoses: 1,
    Pose1: [0.015,0.00,0.00,0,359],
  },
  ID11: {
    Filename: YCB003,
    Description: 003_cracker_box,
    nPoses: 1,
    Pose1: [0.018,0.00,0.00,0,359],
  },
  ID12: {
    Filename: YCB005,
    Description: 005_tomato_soup_can,
    nPoses: 1,
    Pose1: [0.015,0.00,0.00,0,359],
  },
  ID13: {
    Filename: YCB006,
    Description: 006_mustard_bottle,
    nPoses: 1,
    Pose1: [0.079,0.00,0.00,0,179],
  },
  ID14: {
    Filename: YCB008,
    Description: 008_pudding_box,
    nPoses: 1,
    Pose1: [0.06,-1.468,1.0788,0,179],
  },
  ID15: {
    Filename: YCB010,
    Description: 010_potted_meat_can,
    nPoses: 1,
    Pose1: [0.04,0.0,0.0,0,179],
  },
  ID16: {
    Filename: YCB013,
    Description: 013_apple,
    nPoses: 1,
    Pose1: [0.04,0.0,0.0,0,89],
  },
  ID17: {
    Filename: YCB021,
    Description: 021_bleach_cleanser,
    nPoses: 1,
    Pose1: [0.1,0.0,0.0,0,89],
  },
  ID18: {
    Filename: YCB024,
    Description: 024_bowl,
    nPoses: 1,
    Pose1: [0.03,0.0,0.0,0,89],
  },
  ID19: {
    Filename: YCB025,
    Description: 025_mug,
    nPoses: 1,
    Pose1: [0.03,0.0,0.0,0,89],
  },
  ID20: {
    Filename: YCB035,
    Description: 035_power_drill,
    nPoses: 1,
    Pose1: [0.11,1.596,0.026,0,179],
  },
  ID21: {
    Filename: YCB072-a,
    Description: 072-a_toy_airplane,
    nPoses: 1,
    Pose1: [0.092,0.0,0.0,0,359],
  },
  ID22: {
    Filename: YCB055,
    Description: 055_baseball,
    nPoses: 1,
    Pose1: [0.036,0.0,0.0,0,89],
  },
}
