package_path: 'temp' #Gets the package path in roslaunch
kinectMode: 2 # Kinect Movement Mode

# Parameters for DataCollectorV2 code
dataCollectorV2: {
    relative_path: True, # Whether this is relative to the package_path
    directory: '/dataCollected/trainingData/', # Directory to which the PCD, CSV will be saved
    objID: 1, # Object for which data has to be collected
    csvName: 'default.csv', # CSV file to which the data has to be saved
    nData: 25, # Number of dataPoints to be recorded
    homePosesCSV: 'dataCollectionTreeD2.csv', # CSV file in active_vision/misc/ folder to be used to get home poses
    maxRdmSteps: 4, # Max number of random steps to be taken before restarting
    nRdmSearch: 3, # Number times a random search is initiated before going to the next direction
}

# Parameters for policyTester code
policyTester: {
    policy: "PCA_LDA", # Policy to be used (This is set in the roslaunch)
    relative_path: True, # Whether this is relative to the package_path
    directory: '/dataCollected/testData/', # Directory to which the PCD, CSV will be saved
    objID: 1, # Object for which data has to be collected
    csvName: 'default.csv', # CSV file to which the data has to be saved
    storageDir: '/dataCollected/storage/Data_1/', # Directory where the state vector has been stored- Data_0 should never be made, so you must replace this default at runtime.
    csvStVec: 'dataRec_stateVec.csv', # Name of csv inside storageDir
    maxSteps: 5, # Max number of steps to be taken before stopping

    # Parameters for PCA->LDA->LR Policy
    PCALDA: {
      PCAcomponents: 26,
    },
    # Parameters for PCA->LR Policy
    PCA: {
      PCAcomponents: 7,
    },
}


# Parameters for the simulated environment
environment: {
    object_dictionary: [
        "prismAV6x6x6", "Prism 6x6x6",
        "prismAV10x8x4", "Prism 10x8x4",
        "prismAV20x6x5", "Prism 20x6x5",
        "bowlAV", "Bowl",
        "cinderBlockAV", "Cinder Block",
        "handleAV", "Door Handle",
        "gasketAV", "Gasket",
        "drillAV", "Cordless Drill",
    ], #List of object codes and human readable names
    prismAV6x6x6_poses: [0.050,0.000,0.000],
    prismAV10x8x4_poses: [0.060,1.570,0.000,0.070,1.570,1.570],
    prismAV20x6x5_poses: [0.040,0.000,0.000,0.050,1.570,0.000,0.120,1.570,1.570],
    bowlAV_poses: [0.015,0.000,0.000],
    cinderBlockAV_poses: [0.015,0.000,0.000],
    handleAV_poses: [0.015,0.000,0.000],
    gasketAV_poses: [0.015,0.000,0.000],
    drillAV_poses: [0.012,0.000,0.000,0.084,1.459,-0.751,0.082,1.398,-0.014,0.040,0.280,-1.040,0.249,2.860,-0.400,0.068,-1.287,-0.477,0.048,-1.570,1.480],
    object_yaw_limits: [0,89,
        0,179,
        0,179,
        0,179,
        0,1,
        0,89,
        0,359,
        0,179,
        0,359],
    tableCentre: [1.5,0,1],       # Co-ordinates of table centre
    fingerZOffset: 0.0584,        # Z axis offset between gripper hand and finger
    viewsphereRad: 1,
    voxelGridSize: 0.01,          # Voxel Grid size for environment
    voxelGridSizeUnexp: 0.01,     # Voxel Grid size for unexplored point cloud
    scale: 3,                     # Scale value for unexplored point cloud generation
    maxGripperWidth: 0.08,        # Gripper max width
    minGraspQuality: 150,         # Min grasp quality threshold

    addNoise: false,
    depthNoise: 0,
}
